Building with responsive design - TNW website clon
mricanho/Building-with-Responsive-Design pull request #3
Opened 2020-11-09 17:59 UTC by mricanho

I use 2 breakpoints for this project, one at 768px and the other at 1024px.

I use float, flex-box, and grid for the sections.

I tried to reduce the DIV's in HTML for clean code.

2020-11-09 19:07 UTC, descholar-ceo requested changes
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @mricanho   :handshake: :handshake: :handshake: 

# :+1:  Highlights :champagne: :champagne: :champagne: 
:+1: This is good to make it this far, your clone looks like the original website and it is really nice, congratulations on the good work you have done so far and your project is really almost done. Just some touches remaining.
:+1: Your repo looks professional, with very nice PR description, professional readme file and good commit messages, keep it up :muscle:
:+1: You used mobile first approach
:warning: Read the following changes required
# :red_circle: To improve: [Required Changes]
- [x] Latest funding section's header, try to make the right side looks like the original (large screens)

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-11-09 20-57-12](https://user-images.githubusercontent.com/56886064/98584178-2be57f00-22ce-11eb-9877-406c7433bc19.png) | ![Screenshot from 2020-11-09 20-57-55](https://user-images.githubusercontent.com/56886064/98584233-428bd600-22ce-11eb-80a4-bae4bf94842d.png)|
:point_right: Could you see the difference :question: :question: :question: 


- [x] Latest funding section's header, try to make the right side looks like the original (medium screens)

| Your clone | Original page |
| --- | --- |
|![Screenshot from 2020-11-09 20-59-58](https://user-images.githubusercontent.com/56886064/98584440-8e3e7f80-22ce-11eb-9756-73079b29a2c1.png)| ![Screenshot from 2020-11-09 21-00-47](https://user-images.githubusercontent.com/56886064/98584513-a910f400-22ce-11eb-9e2a-dd333c44f3ed.png) |
:point_right: Could you see the difference :question: :question: :question: 

- [x] Fix the footer on mobile screens

| Your clone | Original page |
| --- | --- |
|![Screenshot from 2020-11-09 21-03-22](https://user-images.githubusercontent.com/56886064/98584772-06a54080-22cf-11eb-9202-05b1c8b14dd8.png)| ![Screenshot from 2020-11-09 21-02-38](https://user-images.githubusercontent.com/56886064/98584688-ee352600-22ce-11eb-9cd5-f6bb53f8e1d3.png)|
:point_right: Could you see the difference :question: :question: :question: 

- [ ] The usage of `!important` is highly discouraged
- [ ] Improve the CSS best practices: (Don't repeat yourself = DRY) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright
 __You have used (in your css):__ 
```css
height: 80px; /*=> 4 times*/


width: 100%; /*=> 33 times*/


display: flex; /*=> 63 times*/


display: flex;
flex-direction: column; /*=> 10 times*/
```

====> Advice you can create utility classes which have those properties you want to apply on elements and use them on those elements
Here is the [article which can help you](https://speckyboy.com/good-bad-css-practices/)

# :yellow_circle: Nice to have: [Optional changes]
- [ ] Reduce the width of thenextweb icon which appears on mobile screens
- [ ] Reduce the height of the three first articles on the home pages

Reviewed by [:man_technologist:  descholar-ceo](https://github.com/descholar-ceo)
_slack:_ `@descholar` | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

2020-11-09 19:07 UTC, descholar-ceo commented on README.md
> +  <p>This project is <a href="../Building-with-Responsive-Design/LICENSE">MIT</a> licensed.</p>
[Optional] Try to use markdown language in your readme file

2020-11-09 21:45 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] Keep code DRY as suggested by previous TSE with utilitary selectors. 

> ## Using the Same Rule Repetitively
> 
> A lot of beginners use repetitive rules for each element. If you want to create a rule for multiple elements, use a class attribute instead.
> 
> For instance, instead of repeating color: blue rule for every tags and ID:
> ```
> #intro1 {color: #3498db; font-size: 10px; font-weight: bold;}
> 
> header {color: #3498db; font-size: 20px; background-color: green;}
> 
> #banner {color: #3498db; font-size: 30px; background-image: url(images/static.jpg);}
> ```
> Use a class instead:
> 
> ```
> .blue {color: #3498db;}
> ```



## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-11-09 23:06 UTC, descholar-ceo requested changes
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @mricanho  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] Please fix the heading of latest finding section on both large screens and medium screens, study the following screenshots to understand more about this issue:
#### Large screens:
| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-11-10 00-56-35](https://user-images.githubusercontent.com/56886064/98606364-d3bf7480-22ef-11eb-9671-a50268ad098d.png) | ![Screenshot from 2020-11-10 00-58-58](https://user-images.githubusercontent.com/56886064/98606438-f0f44300-22ef-11eb-81b9-4d1a753e6848.png) |

:point_right: Could you see the difference :question: :question: :question: 

#### Medium screens
| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-11-10 01-04-53](https://user-images.githubusercontent.com/56886064/98606930-ceaef500-22f0-11eb-8906-c8b8a226bb79.png)|![Screenshot from 2020-11-10 01-05-50](https://user-images.githubusercontent.com/56886064/98606984-e5554c00-22f0-11eb-9217-63124fb7fb73.png)|
:point_right: Could you see the difference :question: :question: :question: 

If anything seems to be unclear to you, don't hesitate to contact me for more clarification slack: `@Mugirase Emmanuel` | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2020-11-10 00:29 UTC, abredi approved these changes
### Status: Approved 🙌 🎇
Hi @mricanho , Congratulations 🎊 👏, you did very well on this project.  Kindly fit the following optional enhancements.

[Optional]

- [ ] On the pull request, please specify all the breaking point you used in the project.

Now, you can move ahead.

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/)

2020-11-10 00:49 UTC, merged